url: https://www.neftaliyagua.com.ve
baseurl: 

# Site settings
title: Neftalí Yagua
email: neftali.yagua@gmail.com
description: "Pero Noé halló gracia ante los ojos de Jehová. Genesis 6:8 Presidente de Coderic, S.A. y Pastor de Iglesia LBS Ciudad Alianza."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Omar Yagua
  pic: https://graph.facebook.com/Alfahman/picture?width=225&amp;height=255
  position: Líder de planificación
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Lisbeth Parraga
  pic: https://graph.facebook.com/PARRAGALISBETH/picture?width=225&amp;height=255
  position: Líder de logística
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Gabriel Suárez
  pic: https://graph.facebook.com/gabriel.s.linares.9/picture?width=225&amp;height=255
  position: Líder de desarrollo
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/neftaliyagua
  - title: facebook
    url: https://fb.com/Neftali.Noe.Yagua
  - title: google-plus
    url: https://plus.google.com/+NeftalíYagua
  - title: linkedin
    url: https://ve.linkedin.com/in/neftaliyagua
  - title: instagram
    url: http://instagram.com/neftaliyagua
  - title: bitbucket 
    url: http://bitbucket.org/neftaliyagua
  - title: github
    url: http://github.com/neftaliyagua
  - title: stack-overflow
    url: http://stackoverflow.com/users/2167544/neftali-yagua

# Postal address (add as many lines as necessary)
address:
  - line: URB Diego I Calle 1 Casa 20
  - line: Valencia - Carabobo, 2003, Venezuela

# Build settings
markdown: kramdown
permalink: pretty
