url: http://neftaliyagua.com.ve
baseurl: 

# Site settings
title: Neftalí Yagua
email: despacho@neftaliyagua.com.ve
description: "Ingeniero de Software, Presidente de Coderic, S.A. Autor de los libros El Grano de Mostaza y Mientras Espero. Productor de aplicaciones informáticas, director de proyecto en una variedad de aplicaciones empresariales. Particularmente interesado en el diseño de bases de datos cliente/servidor y relacionales, administración y configuración de servidores, directivas de seguridad y desarrollo en lenguajes de programación. Interés constante en proyectos migratorios, además de en su estrecha interacción con sistemas gestores de bases de datos, desarrollo de paneles de control para sistemas de gestión de datos."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Omar Yagua
  pic: /img/omar_yagua.jpg
  position: Líder de planificación
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Lisbeth Parraga
  pic: /img/lisbeth_parraga.jpg
  position: Líder de logística
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Luis Azuaje
  pic: /img/luis_azuaje.jpg
  position: Líder de desarrollo
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/neftaliyagua
  - title: facebook
    url: https://facebook.com/NeftaliYagua
  - title: google-plus
    url: https://plus.google.com/+NeftalíYagua
  - title: linkedin
    url: https://ve.linkedin.com/in/neftaliyagua
  - title: instagram
    url: http://instagram.com/neftaliyagua
  - title: bitbucket 
    url: http://bitbucket.org/neftaliyagua
  - title: github
    url: http://github.com/neftaliyagua
  - title: stack-overflow
    url: http://stackoverflow.com/users/2167544/neftali-yagua

# Postal address (add as many lines as necessary)
address:
  - line: URB Prados del Norte, Calle C Casa C-35
  - line: San Felipe - Yaracuy, 3210, Venezuela

# Build settings
markdown: kramdown
permalink: pretty
