url: https://neftaliyagua.com
baseurl: https://neftaliyagua.com

# Site settings
title: Neftalí Yagua
email: despacho@neftaliyagua.com.ve
description: "Ingeniero de Software, Productor de aplicaciones informáticas. Autor de los libros El Grano de Mostaza y La Espada de la Justicia. Presidente de Coderic, S.A. Administrador de Servidores en Sunagro."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Omar Yagua
  pic: /img/omar_yagua.jpg
  position: Líder de planificación
  social:
    - title: twitter
      url: #
    - title: facebook-f
      url: #
    - title: stack-overflow
      url: #

- name: Lisbeth Parraga
  pic: /img/lisbeth_parraga.jpg
  position: Líder de logística
  social:
    - title: twitter
      url: #
    - title: facebook-f
      url: #
    - title: linkedin
      url: #

- name: Luis Azuaje
  pic: /img/luis_azuaje.jpg
  position: Líder de desarrollo
  social:
    - title: twitter
      url: #
    - title: facebook-f
      url: #
    - title: google-plus
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: wikipedia-w
#    url: https://es.wikipedia.org/wiki/Neftal%C3%AD_Yagua
  - title: twitter
    url: https://twitter.com/neftaliyagua
  - title: facebook-f
    url: https://facebook.com/NeftaliYagua
  - title: google-plus-g
    url: https://g.co/kgs/66mKR6
  - title: linkedin-in
    url: https://ve.linkedin.com/in/neftaliyagua
  - title: instagram
    url: https://instagram.com/neftaliyagua
  - title: bitbucket 
    url: https://bitbucket.org/neftaliyagua
  - title: github
    url: https://github.com/neftaliyagua
  - title: stack-overflow
    url: https://stackoverflow.com/users/2167544/neftali-yagua


# Build settings
markdown: kramdown
permalink: pretty
